### ISSUE TITLE
TestTimerRunner test fails on Windows when building 

### ISSUE THREAD

**Issue by kourbou** [haciim/study_buddy_2020#21]
The `build` task fails when I try building from the CLI on Windows. My Android SDK is correctly setup in `local.properties`, so I do not think that is the issue. I obtain this:

```
> Task :app:testDebugUnitTest FAILED

TimerRunnerTests > TestTimerRunner FAILED
    org.mockito.exceptions.base.MockitoException at TimerRunnerTests.java:42
        Caused by: java.lang.UnsupportedOperationException at TimerRunnerTests.java:42
            Caused by: java.lang.IllegalArgumentException at TimerRunnerTests.java:42

9 tests completed, 1 failed

FAILURE: Build failed with an exception.
```

**Comment by hingler** [comment]
The issue sounds familiar -- I remember encountering something along these lines but cannot find it in the commit history (pretty sure it was a local configuration thing, bug reports are unfortunately not second-nature yet). However I am unable to duplicate this issue on my end, running off of a freshly-cloned copy of the master branch. Just to double check, this results when running `gradlew build` ?

**Comment by kourbou** [comment]
Yes I just tried again... I ran it off of a fresh clone, seeing as some commits have been made since I opened the issue. My steps are:

1. Clone the repo using `git clone`.
2. Copy in my `local.properties` file which contains:
```
## This file must *NOT* be checked into Version Control Systems,
# as it contains information specific to your local configuration.
#
# Location of the SDK. This is only used by Gradle.
# For customization when using a Version Control System, please read the
# header note.
#Mon May 25 17:57:19 PDT 2020
sdk.dir=C\:\\Users\\[REDACTED]\\AppData\\Local\\Android\\Sdk
```
3. Run `gradlew build`.

Here is [the full Gradle log](https://github.com/haciim/study_buddy_2020/files/4686362/log.txt) with `info` verbosity for your convenience. Here's the interesting part:

```
TimerRunnerTests > TestTimerRunner FAILED
    org.mockito.exceptions.base.MockitoException: 
    Mockito cannot mock this class: class android.os.Handler.

    Mockito can only mock non-private & non-final classes.
    If you're not sure why you're getting this error, please report to the mailing list.


    Java               : 11
    JVM vendor name    : AdoptOpenJDK
    JVM vendor version : 11.0.6+10
    JVM name           : OpenJDK 64-Bit Server VM
    JVM version        : 11.0.6+10
    JVM info           : mixed mode
    OS name            : Windows 10
    OS version         : 10.0


    Underlying exception : java.lang.UnsupportedOperationException: Cannot define class using reflection
        at TimerRunnerTests.TestTimerRunner(TimerRunnerTests.java:42)

        Caused by:
        java.lang.UnsupportedOperationException: Cannot define class using reflection
            at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Unavailable.defineClass(ClassInjector.java:821)
            at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.inject(ClassInjector.java:185)
            at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:187)
            at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:79)
            at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:4376)
            at org.mockito.internal.creation.bytebuddy.SubclassBytecodeGenerator.mockClass(SubclassBytecodeGenerator.java:94)
            at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:37)
            at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:34)
            at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:138)
            at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:346)
            at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:161)
            at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:355)
            at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:32)
            at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMockType(SubclassByteBuddyMockMaker.java:71)
            at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMock(SubclassByteBuddyMockMaker.java:42)
            at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createMock(ByteBuddyMockMaker.java:25)
            at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:35)
            at org.mockito.internal.MockitoCore.mock(MockitoCore.java:63)
            at org.mockito.Mockito.mock(Mockito.java:1729)
            at org.mockito.Mockito.mock(Mockito.java:1642)
            ... 1 more

            Caused by:
            java.lang.IllegalArgumentException: Unknown Java version: 11
                at net.bytebuddy.ClassFileVersion.ofJavaVersion(ClassFileVersion.java:135)
                at net.bytebuddy.ClassFileVersion$VersionLocator$ForJava9CapableVm.locate(ClassFileVersion.java:337)
                at net.bytebuddy.ClassFileVersion.ofThisVm(ClassFileVersion.java:147)
                at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$CreationAction.run(ClassInjector.java:301)
                at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$CreationAction.run(ClassInjector.java:290)
                at java.base/java.security.AccessController.doPrivileged(Native Method)
                at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.<clinit>(ClassInjector.java:70)
                at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:184)
                ... 18 more

```

Perhaps this is because I'm using Java 11 to compile? This is my `java -version`:

```
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)
```

**Comment by hingler** [comment]
Thanks for the additional info -- yeah I think the Java edition would cause this issue, that sounds like what I was dealing with when this issue occurred prior. We've been compiling our application on Java 8, we'll update the README to reflect that.

**Comment by kourbou** [comment]
Just tried with Java 8 (version info below) and I didn't have any errors. Confirms our suspicion! Thanks.
```
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.252-b09, mixed mode)
```
